import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Project additions:
    "coverage/**",
    "docs/design-reference/**",
    // Vendored MapLibre worker, generated by scripts/copy-maplibre-worker.mjs.
    "public/maplibre/**",
    // k6 scripts run in k6's own runtime (its own globals and module
    // resolution), not Node or the browser — linting them against our config
    // reports imports that are correct there and unresolvable here.
    "docs/benchmarks/*.js",
  ]),
]);

export default eslintConfig;
