"""`python -m ml.drift` — compare a recent scoring window to the training set.

## What is compared to what

**Reference:** `features_waste where split = 'train'` — the rows the model was
actually fitted on. Not `val`, not `test`: the question a drift monitor answers
is "does the world still look like what this model learned from", and what it
learned from is `train`.

**Current:** every listing open at `as_of`, with features computed by the same
`FeatureState` the batch job and the endpoint use. Deliberately *not* a re-read
of stored feature rows — a monitor that reads the pipeline's own output would
go on reporting "stable" if the pipeline itself broke. Recomputing from the log
means a pipeline regression shows up here as drift, which is the correct alarm
even though the cause is not the world moving.

## Which features are covered

The **model's** feature list (`ModelA.feature_names`), which excludes
`food_category` — M13 dropped it from the model on measured grounds
(`ml/src/ml/model/dataset.py`). A feature the model never consumes cannot move
a prediction, so a PSI for it would be a number nobody could act on. If it is
ever restored to the model it is covered here automatically, because the list
comes from the artifact rather than from a constant in this file.

## Scoring a production window against simulated training is *meant* to be loud

`--source production` compares real FFE listings to a training set generated by
`ml/src/ml/simulate/`. That will report large PSI on the geography and market
features, and it is not a bug — it is the sim-to-real gap the model card's
`limitations` already names, measured instead of asserted. It is worth running
for exactly that reason, and worth never quoting as "model drift".

## `metric_history` is corpus-side only

FFE reads `listing_risk` and nothing else. Nothing in the product consumes
monitoring output, so it gets no Supabase table — see the M14 brief §7.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any

import numpy as np

from ml.db import connect
from ml.drift.psi import FeatureDrift, band, numeric_psi, psi_from_counts
from ml.features.pipeline import build_observations
from ml.features.spec import OBSERVATION_INTERVAL_HOURS
from ml.features.writer import load_matrix
from ml.model.artifact import ModelA, load_model_a
from ml.serve.sources import EventSource, production_source

__all__ = ["DriftReport", "main", "run_drift"]

#: The score distribution is a probability in [0, 1] and is the one quantity
#: whose bins should not be quantiles of the reference: a well-calibrated model
#: piles most mass near 0 and 1, and quantile edges there would put almost every
#: bucket boundary inside the pile and none across the middle. Fixed decile
#: edges make "the middle emptied out" visible.
SCORE_EDGES = np.linspace(0.0, 1.0, 11)[1:-1]

#: Seven days of hourly observations. The window has to be wide enough to span
#: every hour-of-day and day-of-week the clock features range over, or those
#: features report drift that is really just the window's own shape — see
#: `_current_window`. A week is the shortest span that covers both.
DEFAULT_WINDOW_HOURS = 168


@dataclass(slots=True)
class DriftReport:
    source: str
    as_of: datetime
    model_version: str
    reference_n: int
    current_n: int
    window_hours: int = 168
    score_psi: float = 0.0
    features: list[FeatureDrift] = field(default_factory=list)
    evaluated_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def worst(self) -> list[FeatureDrift]:
        return sorted(self.features, key=lambda d: d.psi, reverse=True)

    @property
    def bands(self) -> dict[str, int]:
        counts: dict[str, int] = {"stable": 0, "moderate": 0, "significant": 0}
        for drift in self.features:
            counts[drift.band] += 1
        return counts

    def metrics_json(self) -> dict[str, Any]:
        worst = self.worst
        return {
            "source": self.source,
            "as_of": self.as_of.isoformat(),
            "reference_n": self.reference_n,
            "current_n": self.current_n,
            "window_hours": self.window_hours,
            "observation_interval_hours": OBSERVATION_INTERVAL_HOURS,
            "score_psi": round(self.score_psi, 6),
            "score_band": band(self.score_psi),
            "features_evaluated": len(self.features),
            "bands": self.bands,
            "worst_feature": worst[0].feature if worst else None,
            "worst_psi": round(worst[0].psi, 6) if worst else None,
        }

    def psi_json(self) -> dict[str, Any]:
        payload: dict[str, Any] = {d.feature: d.as_json() for d in self.features}
        payload["__score__"] = {
            "psi": round(self.score_psi, 6),
            "band": band(self.score_psi),
            "kind": "score",
            "bins": int(SCORE_EDGES.size + 2),
        }
        return payload

    def render(self) -> str:
        lines = [
            "ml drift — PSI vs. the training distribution",
            f"  source          {self.source}",
            f"  as_of           {self.as_of.isoformat()}",
            f"  model           {self.model_version}",
            f"  reference rows  {self.reference_n:,} (split=train)",
            f"  current rows    {self.current_n:,} (open-listing observations over the "
            f"trailing {self.window_hours}h, every {OBSERVATION_INTERVAL_HOURS}h)",
            "",
            f"  score PSI       {self.score_psi:.4f}  [{band(self.score_psi)}]",
            "",
            "  per-feature PSI, worst first:",
        ]
        for drift in self.worst:
            flag = "   " if drift.band == "stable" else " ! "
            lines.append(
                f"  {flag}{drift.feature:<32}{drift.psi:>8.4f}  {drift.band}"
                + (
                    f"   nulls {drift.reference_null_rate:.1%}→{drift.current_null_rate:.1%}"
                    if drift.reference_null_rate or drift.current_null_rate
                    else ""
                )
            )
        counts = self.bands
        lines += [
            "",
            f"  {counts['stable']} stable · {counts['moderate']} moderate · "
            f"{counts['significant']} significant",
            "  thresholds: <0.10 stable, 0.10-0.25 moderate, >0.25 significant",
        ]
        if self.current_n < 100:
            lines.append(
                f"  note: only {self.current_n} listings in the window — PSI over a small "
                "sample is noisy and a 'significant' band here may be sampling, not drift."
            )
        return "\n".join(lines)


def _reference(conn: Any, model: ModelA) -> tuple[dict[str, np.ndarray], np.ndarray]:
    """Training-split feature columns, and the model's scores on them."""
    matrix = load_matrix(conn, list(model.feature_names))
    columns = {name: matrix.column(name, "train") for name in model.feature_names}
    stacked = np.column_stack([columns[name] for name in model.feature_names])
    scores = model.score(stacked) if stacked.size else np.asarray([], dtype=float)
    return columns, scores


def _current_window(
    source: EventSource,
    as_of: datetime,
    model: ModelA,
    window_hours: int,
) -> tuple[dict[str, list[float | None]], np.ndarray, int]:
    """Every open-listing observation in the trailing window, and its score.

    ## Why this calls `build_observations` and not the serving path

    Two earlier versions of this were wrong, and both failures are worth keeping
    written down because they are the same mistake at different depths.

    **First: a snapshot, not a window.** Scoring the listings open at a single
    instant gave `as_of_hour` a PSI of **11.79** — every row shared one clock
    value, against a reference spanning all twenty-four. A maximally drifted
    reading produced by a system in which nothing had drifted.

    **Second: a window the log never caught up with.** Walking an hourly cursor
    forward across `ScoringService` looked right and was not. That service
    replays the log **once**, to its cursor, and then only ever advances the
    clock — which is correct for serving (score against a slightly stale log)
    and wrong here: no *new* listing could appear as the window moved, so the
    population decayed to nothing after about a day. `as_of_dow` sat at 88% on
    a single day and the seven-day window was a lie.

    The fix for both is to stop reimplementing the cadence. `build_observations`
    **is** the cadence — it is the driver that produced every row in
    `features_waste`, interleaving incoming events with due hourly ticks. Using
    it means the current population is generated by the same code as the
    reference population, so a difference between them can only be the data.

    Features still come from `FeatureState.snapshot`, the same call the endpoint
    makes, so nothing about the serving-path guarantee is given up — M13 proved
    the two agree over all 438,093 rows.
    """
    window_start = as_of - timedelta(hours=window_hours)
    columns: dict[str, list[float | None]] = {name: [] for name in model.feature_names}
    vectors: list[list[float]] = []
    observed = 0

    for observation in build_observations(source.replay(as_of)):
        if observation.as_of < window_start or observation.as_of > as_of:
            continue
        observed += 1
        row: list[float] = []
        for name in model.feature_names:
            value = observation.features[name]
            columns[name].append(None if value is None else float(value))
            row.append(float("nan") if value is None else float(value))
        vectors.append(row)

    if not vectors:
        return columns, np.asarray([], dtype=float), observed

    # One vectorised call rather than one per listing: the reference side scores
    # 263k rows the same way, and a per-row loop here would dominate the runtime
    # of the whole job for no difference in the numbers.
    scores = model.score(np.asarray(vectors, dtype=np.float64))
    return columns, scores, observed


def _as_float_array(values: list[float | None]) -> np.ndarray:
    """`None` becomes NaN, which `psi` treats as its own bucket."""
    return np.asarray([float("nan") if v is None else float(v) for v in values], dtype=float)


def resolve_as_of(source_name: str, raw: str | None, source: EventSource) -> datetime:
    if raw is not None and raw != "now":
        parsed = datetime.fromisoformat(raw)
        return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=UTC)
    if raw == "now" or source_name == "production":
        return datetime.now(UTC)
    configured = os.environ.get("ML_SERVE_AS_OF")
    if configured:
        parsed = datetime.fromisoformat(configured)
        return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=UTC)
    latest = source.latest_event_at()
    if latest is None:
        raise SystemExit("the event log is empty; run `make data` first")
    return latest


def write_metric_history(report: DriftReport, dsn: str | None = None) -> int:
    """Append one monitoring row to the corpus database."""
    with connect(dsn) as conn:
        row = conn.execute(
            "insert into public.metric_history (evaluated_at, model_version, metrics, psi) "
            "values (%s, %s, %s, %s) returning id",
            (
                report.evaluated_at,
                report.model_version,
                json.dumps(report.metrics_json(), sort_keys=True),
                json.dumps(report.psi_json(), sort_keys=True),
            ),
        ).fetchone()
    assert row is not None
    return int(row[0])


def run_drift(
    source_name: str = "corpus",
    as_of_raw: str | None = None,
    *,
    dsn: str | None = None,
    source: EventSource | None = None,
    model: ModelA | None = None,
    window_hours: int = DEFAULT_WINDOW_HOURS,
) -> DriftReport:
    resolved_source = source if source is not None else production_source(source_name)
    resolved_model = model if model is not None else load_model_a()
    as_of = resolve_as_of(source_name, as_of_raw, resolved_source)

    with connect(dsn) as conn:
        reference_columns, reference_scores = _reference(conn, resolved_model)

    current_columns, current_scores, _observed = _current_window(
        resolved_source, as_of, resolved_model, window_hours
    )

    report = DriftReport(
        source=source_name,
        as_of=as_of,
        model_version=resolved_model.model_version,
        reference_n=int(reference_scores.size),
        current_n=int(current_scores.size),
        window_hours=window_hours,
    )

    for name in resolved_model.feature_names:
        report.features.append(
            numeric_psi(
                name,
                reference_columns[name],
                _as_float_array(current_columns[name]),
            )
        )

    report.score_psi = psi_from_counts(
        _score_counts(reference_scores), _score_counts(current_scores)
    )
    return report


def _score_counts(scores: np.ndarray) -> np.ndarray:
    if scores.size == 0:
        return np.zeros(SCORE_EDGES.size + 1, dtype=float)
    return np.bincount(
        np.digitize(scores, SCORE_EDGES, right=False), minlength=SCORE_EDGES.size + 1
    ).astype(float)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m ml.drift",
        description="PSI of a recent scoring window against the training distribution.",
    )
    parser.add_argument("--source", choices=("corpus", "production"), default="corpus")
    parser.add_argument("--as-of", default=None, help="ISO-8601 instant, or 'now'")
    parser.add_argument(
        "--window-hours",
        type=int,
        default=DEFAULT_WINDOW_HOURS,
        help=(
            "how far back the scoring window reaches (default: 168). Shorter than ~168 "
            "under-samples hour-of-day and day-of-week and inflates their PSI."
        ),
    )
    parser.add_argument(
        "--no-write",
        action="store_true",
        help="print the report without appending a metric_history row",
    )
    parser.add_argument("--json", action="store_true", help="emit the report as JSON")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = run_drift(
        source_name=args.source,
        as_of_raw=args.as_of,
        window_hours=args.window_hours,
    )

    if args.json:
        print(json.dumps({"metrics": report.metrics_json(), "psi": report.psi_json()}, indent=2))
    else:
        print(report.render())

    if not args.no_write:
        row_id = write_metric_history(report)
        print(f"\nmetric_history row {row_id} written", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
