import type { Metadata } from "next";
import Link from "next/link";
import { InfoIcon } from "lucide-react";

import {
  getMyActivityDaily,
  getMyActivitySummary,
  getNetworkActivityDaily,
  getNetworkOverview,
  getNetworkReach,
} from "@/lib/db";
import type { MyActivitySummary } from "@/lib/db";
import {
  NETWORK_LABELS,
  fulfilment,
  myActivitySeries,
  networkSeries,
  seriesLabels,
} from "@/lib/analytics";
import { ActivityChart } from "@/components/analytics/activity-chart";
import { AnalyticsRealtime } from "@/components/analytics/analytics-realtime";
import { FulfilmentMeter } from "@/components/analytics/fulfilment-meter";
import { ReachChart } from "@/components/analytics/reach-chart";
import { HeroStat, StatTile } from "@/components/analytics/stat-tile";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "Analytics" };

const WINDOW_DAYS = 90;

export default async function AnalyticsPage() {
  // `my_activity_summary` returns no rows when the caller has no organization,
  // which doubles as the gate — no separate lookup needed.
  const summary = await getMyActivitySummary();

  if (!summary) {
    return (
      <div className="grid gap-6">
        <h1 className="text-2xl font-semibold tracking-tight">Analytics</h1>
        <div className="border-border grid gap-3 rounded-xl border border-dashed p-6">
          <h2 className="font-heading text-base font-medium">
            Set up your organization first
          </h2>
          <p className="text-muted-foreground text-sm">
            These charts describe your organization&rsquo;s donations and how
            the network around it is doing. We need to know which side
            you&rsquo;re on.
          </p>
          <Button asChild className="w-fit">
            <Link href="/app/organization">Set up organization</Link>
          </Button>
        </div>
      </div>
    );
  }

  const [myDaily, overview, networkDaily, reach] = await Promise.all([
    getMyActivityDaily(WINDOW_DAYS),
    getNetworkOverview(),
    getNetworkActivityDaily(WINDOW_DAYS),
    getNetworkReach(),
  ]);

  return (
    <div className="grid gap-10">
      <AnalyticsRealtime />

      <div className="grid gap-3">
        <div className="grid gap-1">
          <h1 className="text-2xl font-semibold tracking-tight">Analytics</h1>
          <p className="text-muted-foreground">
            The last {WINDOW_DAYS} days, updating as listings change. Days are
            bucketed in UTC.
          </p>
        </div>

        {/*
         * Spec §9's integrity rule, in the place a visitor would actually be
         * misled. Every figure on this page currently comes from the seed
         * script, and the demo login is public — saying so in the README only
         * would leave the charts looking like production traffic.
         */}
        <div className="bg-brand-amber/12 border-brand-amber/30 flex items-start gap-2 rounded-lg border px-3 py-2 text-sm">
          <InfoIcon
            className="text-brand-amber mt-0.5 size-4 shrink-0"
            aria-hidden="true"
          />
          <span>
            These figures include <strong>seeded demo data</strong> generated by{" "}
            <code className="text-xs">npm run db:seed</code> — not real donation
            traffic.
          </span>
        </div>
      </div>

      <OwnActivity summary={summary} daily={myDaily} />

      <section className="grid gap-6">
        <div className="grid gap-1">
          <h2 className="font-heading text-lg font-medium">
            Across the network
          </h2>
          <p className="text-muted-foreground text-sm">
            Totals for every organization on the platform. Counts only — nothing
            here identifies another organization.
          </p>
        </div>

        {overview ? (
          <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <StatTile
              label="Organizations"
              value={overview.donor_orgs + overview.recipient_orgs}
              hint={`${overview.donor_orgs} donors · ${overview.recipient_orgs} recipients`}
            />
            <StatTile
              label="Open right now"
              value={overview.open_listings}
              hint="Posted and still collectable"
            />
            <StatTile
              label="Claimed, awaiting pickup"
              value={overview.claimed_listings}
            />
            <StatTile
              label="Completed all time"
              value={overview.completed_listings}
              hint={`of ${overview.total_listings} listings posted`}
            />
          </dl>
        ) : null}

        <div className="border-border grid gap-4 rounded-xl border p-6">
          <h3 className="font-heading font-medium">Donations over time</h3>
          <ActivityChart
            points={networkSeries(networkDaily)}
            labels={NETWORK_LABELS}
          />
        </div>

        <div className="border-border grid gap-4 rounded-xl border p-6">
          <div className="grid gap-1">
            <h3 className="font-heading font-medium">How far food travels</h3>
            <p className="text-muted-foreground text-sm">
              Completed donations by the distance between donor and recipient.
            </p>
          </div>
          <ReachChart bands={reach} />
        </div>
      </section>
    </div>
  );
}

/**
 * The caller's own numbers. Which half of the summary is meaningful follows
 * from `role` — a donor posts listings, a recipient makes claims — so the tiles
 * are chosen here rather than showing both and letting half of them read zero.
 */
function OwnActivity({
  summary,
  daily,
}: {
  summary: MyActivitySummary;
  daily: Awaited<ReturnType<typeof getMyActivityDaily>>;
}) {
  const isDonor = summary.role === "donor";
  const labels = seriesLabels(summary.role);
  const points = myActivitySeries(daily, summary.role);

  return (
    <section className="grid gap-6">
      <div className="grid gap-1">
        <h2 className="font-heading text-lg font-medium">Your organization</h2>
        <p className="text-muted-foreground text-sm">
          {isDonor
            ? "Everything you have posted, and how much of it reached someone."
            : "Everything you have claimed, and how much of it you collected."}
        </p>
      </div>

      <div className="border-border grid gap-8 rounded-xl border p-6 sm:grid-cols-2">
        <dl>
          <HeroStat
            label={isDonor ? "Donations completed" : "Pickups collected"}
            value={
              isDonor ? summary.listings_completed : summary.claims_completed
            }
            hint={
              isDonor
                ? `from ${summary.listings_posted} listings posted`
                : `from ${summary.claims_made} claims made`
            }
          />
        </dl>
        <FulfilmentMeter fulfilment={fulfilment(summary)} />
      </div>

      <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {isDonor ? (
          <>
            <StatTile label="Open" value={summary.listings_open} />
            <StatTile label="Claimed" value={summary.listings_claimed} />
            <StatTile
              label="Expired"
              value={summary.listings_expired}
              hint="Pickup window closed unclaimed"
            />
            <StatTile label="Cancelled" value={summary.listings_cancelled} />
          </>
        ) : (
          <>
            <StatTile label="Active claims" value={summary.claims_active} />
            <StatTile label="Collected" value={summary.claims_completed} />
            <StatTile
              label="Released"
              value={summary.claims_released}
              hint="Put back on offer"
            />
            <StatTile label="Claims made" value={summary.claims_made} />
          </>
        )}
      </dl>

      <div className="border-border grid gap-4 rounded-xl border p-6">
        <h3 className="font-heading font-medium">Your activity</h3>
        <ActivityChart points={points} labels={labels} />
      </div>
    </section>
  );
}
